language: R
cache: packages
sudo: true
dist: trusty

addons:
  apt:
    sources:
      - r-packages-precise
    packages:
      - r-base-dev
      - r-recommended

r:
  - oldrel
  - release
  - devel

env:
  global:
    - NOT_CRAN=true R_PKG="$(basename $TRAVIS_REPO_SLUG)"
    # plotly_api_key (for posting to plot.ly)
    - secure: "jlIAFoBGaDWUQDh6oGNb2BgU31/80iioM4y4xwx35yWkGKkNIID1eMEuiIn+/ipLvOVHkPTDS6DYnOtD8EIBpROgAKHFY33gM1h7P6NRxVszzC6WLP2ASnq95DWq36DAC2Oevy05V7nwSRFilPwSt6JLppYUInG+WdaZ+QOSRi4="
    # GITHUB_PAT (for pushing to plotly-test-table)
    - secure: "LHJONgWOo+98vNeFLI7LSJU3RtbMVszlI79GB8CcXmc2mlgM/UtZ5b6RnkNlhmg3Gj1/uObfm/rIybVTwuS1yNpeKv73+gsZOYhobVXiUGVxdRFG/mg5mbqwyWkkuofjPGFlMZCEMgHim37eZzgjSibwVH1LClRDsCoFMCgvgV0="

before_script:
  - git config --global user.email "cpsievert1@gmail.com"
  - git config --global user.name "cpsievert"
  - echo "options(repos = c(CRAN = 'https://cran.rstudio.com')); Sys.setenv('plotly_username' = 'cpsievert')" > ~/.Rprofile
  - git clone https://github.com/cpsievert/plotly-test-table.git ../plotly-test-table
  - "wget -q -O - https://github.com/yihui/crandalf/raw/master/inst/scripts/install-pandoc | bash"
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - Rscript -e 'install.packages("Rserve", type = "source", configure.args = "--enable-R-shlib")'
  - Rscript -e 'if (require(devtools)) { install.packages("devtools") }'
  - Rscript -e 'devtools::update_packages("devtools")'
  - Rscript -e 'devtools::install_deps(dependencies = TRUE)'
  - cd ..; rm -f *.tar.gz; R CMD build $R_PKG
  - R CMD INSTALL ${R_PKG}_*.tar.gz

script:
  # run R CMD check on the non-pull request build
  - sh -c "if [ '$TRAVIS_PULL_REQUEST' = 'false' ]; then R CMD check ${R_PKG}_*.tar.gz --no-manual; fi"
  # we do some fancy stuff on the pull request build that confuses R CMD check
  - sh -c "if [ '$TRAVIS_PULL_REQUEST' != 'false' ]; then Rscript -e 'source(\"plotly/tests/testthat.R\", chdir = T)'; fi"

after_success:
  - cd plotly-test-table
  - Rscript ../plotly/inst/build-push-comment.R
